### ISSUE TITLE
`disabled` option for choices does not work

### ISSUE THREAD

**Issue by SurionA** [terkelg/prompts#103]
Hi

First thank you for your great work !
I am playing with the select and multi-select but I am not able to disabled some options.
After a quick look, I can submit a small fix:

* makes disabled options works on select
* makes disabled options works on multi-select
* multi-select does not submit on disabled option (same behavior as select )

**Comment by terkelg** [comment]
Awesome, thanks @SurionA

**Comment by terkelg** [comment]
Published in [v1.2.0](https://github.com/terkelg/prompts/releases/tag/v1.2.0). Thanks!
