### ISSUE TITLE
unexpected initial behavior in text type

### ISSUE THREAD

**Issue by puckey** [terkelg/prompts#105]
I have the following prompt to allow the user to edit a string:
```js
        await prompts({
          type: 'text',
          name: 'value',
          initial: 'Edit me!'
        });
```

Here I would expect the initial value of the text to be the value contained in `initial`. This would allow the user to edit the text as wanted. Instead `initial` is only used as a default value when you press enter without having entered anything.

**Comment by terkelg** [comment]
Initial is the `default` value. It can be a bit confusing, but `default` is a reserved word

**Comment by terkelg** [comment]
I'm closing this one for now - Let me know if you have other questions or suggestions.
