### ISSUE TITLE
Support dot notation in question `name`

### ISSUE THREAD

**Issue by tunnckoCore** [terkelg/prompts#106]
So it will allow questions like

```
{
  type: 'text',
  name: 'author.username',
  message: 'What is your GitHub username?',
  initial: gitconfig.user.username,
}
```

**Comment by terkelg** [comment]
Going to close this one for now unless someone do a PR

**Comment by terkelg** [comment]
I added a label. Can you please explain what doesn't make sense?
You're always welcome to do a PR we can review and talk about.
