### ISSUE TITLE
Add a date/time prompt

### ISSUE THREAD

**Issue by macmichael01** [terkelg/prompts#109]
It would be nice to have a prompt that deals with date and time.

**Comment by terkelg** [comment]
Hey @macmichael01 - Thanks for the issue. I totally agree with you. Could you be open to giving this a try? I'm a bit busy at the moment and won't have the time to do it.

**Comment by macmichael01** [comment]
My team doesn't have an immediate need for this. Thought it would be a nice to have. If I can allocate time and resources, I will task one of my engineers to help implement this.

**Comment by terkelg** [comment]
Thanks @macmichael01. That could be awesome. I appreciate it. Please let me know if you have time to implement this.

**Comment by terkelg** [comment]
Closing as this is currently being implemented 👍
