### ISSUE TITLE
Add a regex prompt

### ISSUE THREAD

**Issue by macmichael01** [terkelg/prompts#110]
It would be nice to have a prompt that deals specifically with regex.

**Comment by terkelg** [comment]
How would this work and can you provide an example?

**Comment by macmichael01** [comment]
I've seen other prompt modules which have a `pattern` param. I suppose one could easily perform a regex though defining the validation param. Maybe this is unnecessary. Thought it would serve as a  convenience for developers.

**Comment by terkelg** [comment]
Agree. It could be a nice-to-have. I'm super busy, so I'll close this for now unless someone feels like implementing it.
