### ISSUE TITLE
How can I disable some choice base on previous answer?

### ISSUE THREAD

**Issue by kamontat** [terkelg/prompts#114]

**Comment by gebeto** [comment]
Just use `.filter` to remove chices or `.map` to disable

# Code
![filter](https://user-images.githubusercontent.com/13422799/49500122-9b4bcc00-f878-11e8-86fe-9c442d0c9a67.png)

# Filter example
> There are shown only that names that includes chars entered in first prompt

![filter](https://user-images.githubusercontent.com/13422799/49500143-a6066100-f878-11e8-886b-bae98b0eb545.gif)

# Map example
> There are disabled names that includes chars entered in first prompt

![map](https://user-images.githubusercontent.com/13422799/49500385-4b213980-f879-11e8-9565-0b97b69ffe1b.gif)

**Comment by gebeto** [comment]
Just read the docs there https://github.com/terkelg/prompts#-prompt-objects

Each property be of type `function` and will be invoked right before prompting the user.
so you can make something like that and it will work
![screen shot 2018-12-05 at 11 30 27 am](https://user-images.githubusercontent.com/13422799/49503891-2cbf3c00-f881-11e8-8558-bd018f1f1f77.png)


 ```js
```

**Comment by kamontat** [comment]
In the document, I didn't see that choices also accept function. Sorry.
