### ISSUE TITLE
Improve UX for date prompt (PR #116)

### ISSUE THREAD

**Issue by DrunkenPoney** [terkelg/prompts#117]
Just creating an issue for what @terkelg mentionned here:
https://github.com/terkelg/prompts/pull/116#issuecomment-445554675

> Here are some ideas for even better UX:
>
> - [x] Cycle year/date/month with <kbd>tab</kbd>
> - [x] Make it possible to type numbers - like in the Number prompt
  > - [x] Option to change format (`mm/dd/yy`, `dd/mm/yy`)
> - [x] Validate function like in the Number prompt
>
> Similar to [date-prompt](https://github.com/derhuerst/date-prompt). Let me know if you're up for some of it. I can possibly help out with some of it in the future.

I'm probably gonna start working on it by the end of the week if not already done by someone else.

<hr>

### Edit
For the fourth point, wouldn't min and max be enough?

**Comment by terkelg** [comment]
Thank you @DrunkenPoney! 
![111](https://user-images.githubusercontent.com/2302254/49718496-8c8b5d80-fc5a-11e8-86d9-5119a187e33e.gif)

**Comment by DrunkenPoney** [comment]
@terkelg How do you want to implement the option to change format? Use [`Intl.DateTimeFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat) as option type? Create a new library? Use an existing library?

**Comment by terkelg** [comment]
Hi @DrunkenPoney! I would prefer to not use external libraries if possible. Let me create a branch real quick - sorry, didn't see your comment

**Comment by gebeto** [comment]
Hey, @terkelg , can you up to date the `date-prompt` branch? @DrunkenPoney was send me a [pull request](https://github.com/gebeto/prompts/pull/1) and I've merge it to `master`

**Comment by terkelg** [comment]
Thanks @gebeto. I assume 607ab96 fixes it right?

**Comment by gebeto** [comment]
@terkelg, Yep!

**Comment by DrunkenPoney** [comment]
@terkelg Done! ;)
#135
