### ISSUE TITLE
Initialization of 'this.first' in Prompt class overwrites 'first()' method on subclasses

### ISSUE THREAD

**Issue by rbuckton** [terkelg/prompts#120]
It seems like a number of the `Prompt` subclasses have a `first()` method that gets overwritten by the `Prompt` constructor:

- https://github.com/terkelg/prompts/blob/master/lib/elements/autocomplete.js#L126 - Example of a `first()` method, but occurs in other elements.
- https://github.com/terkelg/prompts/blob/master/lib/elements/prompt.js#L18 - Overwrites `first` with `false`.

**Comment by terkelg** [comment]
Ah! Thank you @rbuckton - nice catch. Thanks for reporting the issue. I the long term I would love to rewrite Prompts to TypeScript which would safeguard against stuff like this.

Renaming `first` in `prompt.js` to something like `_first` isprobabbly the best solution.

**Comment by terkelg** [comment]
Should be fixed in 3bef58c 👍
