### ISSUE TITLE
Fallback not working on autocomplete

### ISSUE THREAD

**Issue by casalaina** [terkelg/prompts#121]
Maybe I'm misunderstanding the purpose of fallbacks for autocomplete, but I'm expecting it to come up if I type something that's not one of the choices. Right now, all I see is `undefined`, and I can't figure out how I'd get to see that fallback message at all.

![prompts](https://user-images.githubusercontent.com/458536/50655928-ea793f80-0f91-11e9-9fa7-2ad85ab760b6.gif)

Is there currently a way to limit an autocomplete type prompt to the predefined choices and/or validate it to that list?

**Comment by terkelg** [comment]
You're right - it should show up when nothing matches.

**Comment by terkelg** [comment]
This is will be fixed in the next release thanks to @lumio and @DrunkenPoney
