### ISSUE TITLE
Undefined response in multiselect (async / await)

### ISSUE THREAD

**Issue by sebRomeo** [terkelg/prompts#122]
Hi, I don't have so much info on this:

I have a select prompt that randomly respond correctly / undefined:
* It is running in a test environnment in nested async / awaits functions context
* I have tried other cli-select extensions like inquirer or cli-select and both where working correctly
* I have checked that all my async calls where awaited correctly

Here is my code:
``` javascript
let choice = await prompts({
        type: 'select',
        name: 'action',
        message: 'What to do next ?',
        choices: ['Continue and replay last', 'Continue', 'Exit', 'Replay from 2 last', 'Replay from 5 last'],
    });```

I dont have so much infos further...hope it will be useful ;)

**Comment by DrunkenPoney** [comment]
The `choices` option needs to be an array of objects with at least a `value` property. 
For example:

```javascript
let {action} = await prompts({
    type: 'select',
    name: 'action',
    message: 'What to do next ?',
    choices: [
        { title: 'Continue and replay last', value: 1 },
        { title: 'Continue', value: 2 },
        { title: 'Exit', value: 3 },
        { title: 'Replay from 2 last', value: 4 },
        { title: 'Replay from 5 last', value: 5 }
    ],
});
```

If no title property is specified, the value will be used for both the title and the value. See [here](https://github.com/terkelg/prompts#options-6) for more information.

@terkelg I think this should be fixed so when only a string is specified as a choice it uses this string for both the title and the value or use the choice index as the value. I think we should also set a _default_ value when only the title is specified.

**Comment by terkelg** [comment]
I think that's a good idea @DrunkenPoney - thank you for the input!

**Comment by lumio** [comment]
This should be resolved by now, right? Gonna close it :)
