### ISSUE TITLE
Examples won't work on Node 6 (async/await not supported)

### ISSUE THREAD

**Issue by ssotomayor** [terkelg/prompts#125]
[Async/Await is not supported in Node 6](https://node.green/#ES2017-features-async-functions), i'm using a [lib](https://www.npmjs.com/package/asyncawait) to test it out, but pointing out that in the docs, or upping the needed version on the docs would be a nice.

Best.

**Comment by terkelg** [comment]
We already take care of that in [`index.js`](https://github.com/terkelg/prompts/blob/master/index.js). There's a dist version that is build in prepublish hook
