### ISSUE TITLE
Select prompt does not await correctly when called from an object

### ISSUE THREAD

**Issue by vikepic** [terkelg/prompts#129]
I wrote a little test file to reproduce the issue:

```
#!/usr/bin/env node
'use strict';

const prompts = require('prompts');

const obj = {
	prompt1 : async () => await prompts(
		{
			type: 'select',
			name: 'project',
			message: 'Pick a project',
			choices: [
				{title: '1', value: '1'},
				{title: '2', value: '2'}
			]
		}
	)
}

console.log(obj.prompt1());
```

This yields

```
❯ ./test.js
? Pick a project › - Use arrow-keys. Return to submit.
❯  1
   2Promise { <pending> }
```

And, what is even worse, after switching the choice with the arrow keys:

```
❯ ./test.js
? Pick a project › - Use arrow-keys. Return to submit.
? Pick a project › - Use arrow-keys. Return to submit.
   1
❯  2
```

It appears to me that the promise is being satisfied prematurely.

I'm using MacOS Mojave 10.14.2

```
❯ node --version
v8.11.4
❯ npm --version
5.6.0
```

Thanks for reading!

**Comment by terkelg** [comment]
Hi @vikepic  - Sorry for the late reply. Thanks for reporting the issue. Do you mind taking a stab at this? I won't be able to look at Prompt issues in the next few weeks because I'm moving.

**Comment by vikepic** [comment]
I'll try to go at it. I'll be moving soon too, so i might not be able to make it either 😅

**Comment by DrunkenPoney** [comment]
@vikepic It's cause you're not awaiting the `obj.prompt1()` before calling console.log. Try removing the console.log at the end or do the following...
 ```javascript
'use strict';

const prompts = require('prompts');

const obj = {
	prompt1 : () => prompts({
			type: 'select',
			name: 'project',
			message: 'Pick a project',
			choices: [
				{title: '1', value: '1'},
				{title: '2', value: '2'}
			]
		})
}

(async () => {
	console.log(await obj.prompt1());
})();
```

**Comment by terkelg** [comment]
Thank you @DrunkenPoney - I somehow overlooked that!

**Comment by vikepic** [comment]
Thanks @terkelg and @DrunkenPoney !

At the time of the writing I was still getting my head around async stuff. Now I'm proud to say that I've successfully implemented this package in a project and works beautifully. It's much lighter than Inquirer, what I was using at the moment.

Thanks again!
