### ISSUE TITLE
Autocomplete support for pagination

### ISSUE THREAD

**Issue by softprops** [terkelg/prompts#130]
I like that the autocomplete type limits the number of options you see by default. 

Im building a terminal ui for a list that I expect to grow but I want type filtering that the autocomplete type provides. I'd also like users to discover choices by navigating with up and down arrows. It would be great if the list paged through options once the user hits the display limit.

**Comment by terkelg** [comment]
Thank you for the PR. I like the idea – this could be a great enhancement for future releases. 👍

**Comment by softprops** [comment]
I'm not sure how to go about doing this myself if I'd be happy to try with some pointers

**Comment by softprops** [comment]
awesome!!!

 @terkelg how soon might we see this this in a release?

**Comment by terkelg** [comment]
It will be released in the upcoming week 👍

**Comment by softprops** [comment]
I posted a comment in the pull https://github.com/terkelg/prompts/pull/136#issuecomment-469060613 about an issue I had when testing the latest from git sha. Im not sure if that should be a separate gh issue if I'm doing something wrong. In short I see the pagination pages but I can't figure out how to scroll past the first page of results
