### ISSUE TITLE
Add functionality to skip prompts

### ISSUE THREAD

**Issue by jkwohlfahrt** [terkelg/prompts#132]
I'm really enjoying the prompts module, but would love added functionality for skipping prompts, and using command line options instead, similar to how overrides were implemented in the `prompt` npm package, here: https://github.com/flatiron/prompt#skipping-prompts. Overrides like these provide tremendous ease of use, especially for cli commands that have lots of nested menus and options.

**Comment by lumio** [comment]
Definitely something we should look into.

I implemented something for one of my terminal programs that just skips certain questions if they are already present. But it would be nice if `prompts` can handle those similar to `prompt`.

I wonder however how `prompts` should react if some questions are unanswered and not overwritten. Are the overwritten questions still being rendered with their new values as defaults or should just the missing questions be rendered?

**Comment by jkwohlfahrt** [comment]
@lumio I feel that just the missing questions should be rendered. We use override functionality on our homegrown cli tooling, and only rendering the questions that are left really speeds up the use of the tooling.

**Comment by lumio** [comment]
@jkwohlfahrt it makes sense. Why would you overwrite it in the first place then

**Comment by jkwohlfahrt** [comment]
I've use the prompt override functionality fairly heavily in the past, to quickly execute commands that have lots of prompts involved. For instance, we have CLI commands that call APIs with several prompted parameters. Often times, especially for testing purposes, our engineering team needs to make the same call over and over again, largely with the same parameters. Overwriting the prompts takes away a lot of the monotony of gong through the same steps over and over again. Does that answer your question at all, @lumio ? Not sure I fully understand what you're asking.

**Comment by lumio** [comment]
@jkwohlfahrt sorry for the confusion. I meant it in a rhetorical way 😄 
I fully agree with you! If you overwrite the answers of your questions, you don't want to render them any longer.

I might have a look into it tomorrow.

**Comment by terkelg** [comment]
This will be included in the next release, thank you guys!

**Comment by giacomocerquone** [comment]
typings are missing here, I'll add it ASAP
