### ISSUE TITLE
ALT + <key> prints `undefined`

### ISSUE THREAD

**Issue by DrunkenPoney** [terkelg/prompts#145]
### Description
I was looking for a way to do [this](https://github.com/terkelg/prompts/blob/d320cd78d409d0bef7c1928286abf6c5a2ba176c/lib/elements/autocomplete.js#L134), but I realized it wouldn't be possible with the <kbd>ctrl</kbd> key so I tried with <kbd>alt</kbd> instead and I found that pressing <kbd>alt</kbd> with any other letter key will print _undefined_.

### To Reproduce
Just press <kbd>alt</kbd>+_key_ on any prompt accepting user input like text or autocomplete.

### Expected behavior
Nothing!

### System
- OS: Linux
- Terminal: Linux terminal (bash)
- Node: v11.10.0

**Comment by terkelg** [comment]
Thank you for reporting this!

**Comment by trustedtomato** [comment]
I can confirm. Cannot paste text into Termux because Paste doesn't work in a prompt and Ctrl+Alt+V seems to output undefined.

### System
OS: Android
Terminal: Termux (0.66)
Node: v11.0.0
