### ISSUE TITLE
how can I pipe my answers to another command

### ISSUE THREAD

**Issue by a7madgamal** [terkelg/prompts#147]
### Is your feature request related to a problem?
more like a question than a feature request.
I'm using prompts to define some options I need for a yarn command
how can I get the selected options and pass them to another command or do I have to use node APIs instead of running `yarn run commandWithOptionsBasedOnCollectedAnswers`

**Comment by a7madgamal** [comment]
we have `ENTRY=something yarn dev:someSubCommand` and I just want to run `yarn dev` which should be just a simple `prompts` script to generate and run the correct command

**Comment by lumio** [comment]
Hi @a7madgamal 

What exactly do you mean? As far as I understand your question: you want to show a prompt with `prompts` and then depending on the collected values run other `yarn` commands or `node` instances?

This is possible with [nodes `child_process`](https://nodejs.org/api/child_process.html).

```js
( async () => {
  const prompts = require('prompts');

  const response = await prompts({
      type: 'number',
      name: 'value',
      message: 'How old are you?',
      validate: value => value < 18 ? `Nightclub is 18+ only` : true
  });

  console.log(response); // => { value: 24 }
  // pass collected values to other commands by either running them
  // with require( 'child_process').exec( 'command' )
} )();
