### ISSUE TITLE
Using select with message longer than terminal width duplicates the message.

### ISSUE THREAD

**Issue by eahefnawy** [terkelg/prompts#153]
### Describe the bug
Using select with message longer than terminal width duplicates the message and breaks the UI.

![prompts-bug](https://user-images.githubusercontent.com/2312463/55735462-088b8b80-5a2a-11e9-92ba-399ffc1a225e.gif)

### To Reproduce
Just run this script in a relatively narrow terminal window:

```js
const prompts = require('prompts')

const runPrompt = async () => {
  const selected = await prompts(
    {
      type: 'select',
      name: 'template',
      message: 'What would you like to create in this directory?',
      choices: [
        { title: 'My Own Component', value: 'component' },
        { title: 'Function', value: 'function' },
        { title: 'API', value: 'api' },
        { title: 'Website', value: 'website' },
        { title: 'Realtime Application', value: 'realtime-app' },
        { title: 'Chat Application', value: 'chat-app' },
        { title: 'Websocket Backend', value: 'websocket-backend' }
      ],
      initial: 0
    },
    {
      onCancel: () => process.exit(0)
    }
  )
  console.log(selected)
}

runPrompt()


```

### Expected behavior
It should detect terminal width and adjust cursor automatically. It shouldn't duplicate the message.

### System

- OS: macOS 10.14.2
- Terminal: iTerm
- Node version: `v11.12.0`

### Additional context
Might be related to #89

**Comment by daKmoR** [comment]
I can verify this - but it doesn't even need to be a small screen - as soon as the message is multi-line the bug appears 😭 
```js
const questions = [{
  type: 'select',
  name: 'rootType',
  message: 'What would you like to do today?\n  More info on the full flow can be found at\n  https://open-wc.org/create/',
  choices: [
    { title: 'Scaffold a new project', value: 'scaffold' },
    { title: 'Upgrade an existing project', value: 'upgrade' },
    { title: 'Nah, I am fine thanks! => exit', value: 'exit' },
  ],
  initial: 1,
}];
```

**Comment by terkelg** [comment]
Thank you for reporting this bug

**Comment by dangercard** [comment]
I've been reading my code for hours thinking I had made a mistake. Good thing I checked here. Thanks for the report!

**Comment by dsosborn** [comment]
The same thing happens if the list of options is taller than the window.
