### ISSUE TITLE
No license key in package.json

### ISSUE THREAD

**Issue by ishanisuchak** [terkelg/prompts#154]
### Issue
The package has MIT license but the license key is not present in the package.json of the installed package. It should be present there as well for license checkers to read.

### To Reproduce
Steps to reproduce the behavior

1. Install the package
2. Check the package.json in node_modules/prompts

### Expected behavior
It should be present in the package.json as well for license checkers to read

### System

- OS: Windows 10
- Terminal: PowerShell, SharePoint online management shell
- Node version: 8.15.0

**Comment by lumio** [comment]
Tested with `npm v6.4.1`, `npm v6.9.0` and `yarn v1.15.2`.

`npm` does a lot of things to the installed package and its `package.json`, but the `license` field is still there. Even the license file.
`yarn` just uses the default `package.json`.

Even though I tested this on my Mac, I don't see an issue here. Especially as the license file is being installed as well.

What `npm` version do you use?

**Comment by terkelg** [comment]
Closing for now. Thank you @lumio
