### ISSUE TITLE
Basic example not working...?

### ISSUE THREAD

**Issue by totszwai** [terkelg/prompts#155]
### Describe the bug
Use the most basic example code 
```
const prompts = require('prompts');
 
const response = await prompts({
    type: 'number',
    name: 'value',
    message: 'How old are you?',
    validate: value => value < 18 ? `Nightclub is 18+ only` : true
});
 
console.log(response); // => { value: 24 }
```
Gets error:
```
const response = await prompts({
                 ^^^^^

SyntaxError: await is only valid in async function
```

Only works without the await keyword, is your prompts function not returning a Promise?

**Comment by lukeed** [comment]
Hey there,

It does return a promise. But as you can see in the error message: `await is only valid in async function`

The README example does not include the wrapping `async function () { ... }` for illustration purposes only. For a true example, check out the [`example.js`](https://github.com/terkelg/prompts/blob/master/example.js) file.

Hope that helps~!

**Comment by totszwai** [comment]
Thanks, ended up using inquirer

**Comment by lumio** [comment]
Even though the ticket got closed, I think it might be a good idea to have a running example in the README. If someone is experienced with async/await, it should be easy to understand, that a wrapping function is missing here.

But it must be frustrating for someone who is not familiar with the concept, or someone who just wants to test out all different prompt libraries. Therefore I would say, we actually add the wrapping async IIFE. Shouldn't be such a big deal imo 😃
