### ISSUE TITLE
Configurable prompt symbols

### ISSUE THREAD

**Issue by lauriejim** [terkelg/prompts#16]
Is it actually possible to customize the question prefix `?` with emoji for exemple.
It could be really cool to offert a more contextual experience.

And nice job for this project 👍

**Comment by lukeed** [comment]
I think that the furthest I'd take this is allowing a specific `prefix` per prompt.

**Comment by terkelg** [comment]
@lukeed per prompt object or prompt function? I guess we can make it a option

**Comment by lukeed** [comment]
I don't need this, but I would guess those who want it would want per object.

**Comment by olstenlarck** [comment]
Per object, yea. Which in turn to be able to be function too. Don't need too but sounds good thing.

**Comment by terkelg** [comment]
Perfect! This will be implemented.

**Comment by terkelg** [comment]
I think what we do is to make a prompt option called `symbols` that will get merged with the [default]() styles object in the base elements.

**Comment by terkelg** [comment]
`opt.symbols` could look like this:
```
{
  prompt: { done, aborted, default },
  delimiter: { default },
  item: { expanded, default }
}
```
Is this too much?

**Comment by terkelg** [comment]
Closing for now

**Comment by lauriejim** [comment]
@terkelg `opt.symbols` is a good option.

**Comment by zed-k** [comment]
Has this idea been abandonned?
Being able to customize the output would be a really nice addition without adding much complexity.

**Comment by terkelg** [comment]
This is on hold for now – I'll look into this for a v2

**Comment by aral** [comment]
I just added very quick and dirty custom symbol support for the confirmation prompt in my branch: https://github.com/aral/prompts/tree/custom-symbols-for-confirm

To use:

```js
        {
            type: 'confirm',
            name: 'confirmed',
            message: 'Can you confirm?',
            symbol: () => (done, aborted) => aborted ? '❌' : done ? '🎉' : '🧐',
        }
```

In case it helps as a stopgap for anyone else.
