### ISSUE TITLE
Option to disable instruction text on Multiselect

### ISSUE THREAD

**Issue by stevenmasci** [terkelg/prompts#173]
Hi, is it possible to disable the instruction text on the Multiselect prompt?

If not, would it be possible to implement a parameter option "instructions" of type `boolean` for the Multiselect prompt to toggle instructions on and off?

Thanks.

**Comment by tdjsnelling** [comment]
+1, this would be a great addition.

**Comment by wilmouths** [comment]
I created a PR (#174) that was merged for this option

**Comment by DrunkenPoney** [comment]
@terkelg I think this one can be closed. :wink:

**Comment by stevenmasci** [comment]
Great! Thank you.
