### ISSUE TITLE
Await is only valid in async function

### ISSUE THREAD

**Issue by SCKelemen** [terkelg/prompts#18]
This is probably some configuration mistake, but when I run the example code, I get the following error:
![image](https://user-images.githubusercontent.com/4325375/36810628-4159fd54-1c99-11e8-9309-2a7b4e7d3362.png)

Code: 
```js
const prompt = require('prompts');

let questions = [
    {
        type: 'text',
        name: 'username',
        message: 'What is your GitHub username?'
    },
    {
        type: 'number',
        name: 'age',
        message: 'How old are you?'
    },
    {
        type: 'text',
        name: 'about',
        message: 'Tell somethign about yourself',
        initial: 'Why should I?'
    }
];

let response = await prompts(questions);
```

**Comment by lukeed** [comment]
Yeah, it's illustrative.

**Comment by olstenlarck** [comment]
Of course. Global `await` is still not allowed, may be one day, but it's not sure.

The examples assume it is in async function.

**Comment by SCKelemen** [comment]
Okay, I thought that was the issue. Thanks guys. Nice work, btw.

**Comment by terkelg** [comment]
Thanks @SCKelemen. I appreciate you took the time to make an issue. @olstenlarck please don't use phrases like ['of course' or similar in this repo](https://css-tricks.com/words-avoid-educational-writing/).

**Comment by olstenlarck** [comment]
Uh oh, okey. Thanks for the link. :)

**Comment by tymoor** [comment]
> Of course. Global `await` is still not allowed, may be one day, but it's not sure.
> 
> The examples assume it is in async function.
> 
> ```js
> async function run() {
>   let response = await prompts(questions);
> }
> 
> run()
> ```

Thanks for this - I think adding these few lines to the getting started section of the README.md would make it easier for people just trying out the library.
