### ISSUE TITLE
instructions option doesnt toggle instruction

### ISSUE THREAD

**Issue by vardrop** [terkelg/prompts#184]
### Describe the bug
When trying to turn off instructions it still displays instructions.

### To Reproduce
```js
const prompts = require('prompts');

(async () => {
  const response = await prompts({
    type: 'multiselect',
    name: 'value',
    message: 'This doesnt seem right',
    choices: [
        { title: 'Red', value: '#ff0000' },
        { title: 'Green', value: '#00ff00' },
        { title: 'Blue', value: '#0000ff' }
      ],
    instructions: false,
  });

/**
? This doesnt seem right »
Instructions:
    ↑/↓: Highlight option
    ←/→/[space]: Toggle selection
    enter/return: Complete answer

( )  Red
( )  Green
( )  Blue
*/
})();
```

### Expected behavior
When setting instructions to `false` it shouldnt display instructions.

### System

- OS: Microsoft Windows 10 Pro N 10.0.18362 Build 18362
- Terminal: cmder(cmd)
- Node version: v12.5.0

### Additional context
```
$ npm show prompts version
2.1.0
```

**Comment by mguirao** [comment]
I'm having a similar issue with Cmder.
I'm using text type, and i'm unable to see what i'm typing.
But when i validate, it works nonetheless.
I'm interested in an investigation.

**Comment by terkelg** [comment]
Thank you. This is fixed in master and will be a part of the next release #177 #216
