### ISSUE TITLE
Possible typo in the source code

### ISSUE THREAD

**Issue by olstenlarck** [terkelg/prompts#19]
Heya. As ususal, i always review the whole code of libraries or whatever.

So found that the `this.rl` here https://github.com/terkelg/prompts/blob/230c1a674965a065f931012be74af3ca523f1fb0/lib/elements/prompt.js#L18-L19

probably is meant to be the `rl` const, because the `this.rl` is not defined in any other place in the code base, even in that file.

**Comment by terkelg** [comment]
Interesting - I'll have a look at this tonight

**Comment by olstenlarck** [comment]
Yea, it's a bit sad that ESLint can't (?) handle such things. If there is such rule would be great.

**Comment by terkelg** [comment]
Thanks. I've removed readline in the 'keypress' branch.
