### ISSUE TITLE
Allow Question prompts and validation to be right justified and left padded from start of terminal prompt

### ISSUE THREAD

**Issue by wakatara** [terkelg/prompts#196]
### Is your feature request related to a problem?

I would like to right justify the text of the questions so they are space padded from the left hand terminal prompt. Mostly because I think this would look very cool and look very clean. There may be a way to do this that doesn't need to be built into prompts, but I was unable to figure it out (and I apologize if there is - I am new to the javascript ecosystem though not new to programming)

### Describe the solution you'd like

I'd like a set of questions to appear in this sort of order and be right justified and left padded by spaces.

>            Bed by midnight
>                  Slept 7h+
>          Language practice
>                Talk to Mom

### Describe alternatives you've considered

I tried to calculate left padding on the fly to justify the things. It did not go well. 

### Additional context

I am also trying to built it this way because I intend to follow the prompt with a new prompt type which includes a consistency graph for reference.

**Comment by elliot-nelson** [comment]
I think you can do this today using left-padding as you describe, an example:

```
async function main() {
    // List of question descriptions and their names
    let questions = [
        ['Bed by midnight', 'midnight'],
        ['Slept 7h+', 'sleep'],
        ['Language practice', 'language'],
        ['Talk to Mom', 'mom']
    ];

    // Right-pad the question descriptions
    let longest = Math.max(...questions.map(q => q[0].length));
    questions.forEach(q => {
        q[0] = q[0].padStart(longest);
    });

    // Prompt the user
    let answers = await prompts(questions.map(q => {
        return { message: q[0], name: q[1], type: 'confirm' };
    }));

    console.log(answers);
}
main();
```

Output:
```
✔   Bed by midnight … yes
✔         Slept 7h+ … yes
✔ Language practice … no
✔       Talk to Mom … yes
{ midnight: true, sleep: true, language: false, mom: true }
```

If you wanted additional indentation, you could arbitrarily increase the value you pass to `padStart`.

(If I misunderstood the goal, let me know.)

**Comment by wakatara** [comment]
@elliot-nelson  I have to admit I am embarrassed I did not know about the padStart function but yes, I cottoned on from what you had above and got this to work exactly the way I wanted. Thank you so much for the help, was exactly what I wanted. generalizing it to work for the larger CLI app now. merci!
