### ISSUE TITLE
Unexpected prompt/question to evaluate question type

### ISSUE THREAD

**Issue by vaffonso** [terkelg/prompts#198]
### Describe the bug
Function signature does not return the previous prompt but the current instead.
As per documentation, function signature suppose to return previous prompt object (3rd attribute)

### To Reproduce

1. Create question list with 2 items
2. Type of second question type should use function to validate if name of previous prompt is the name of the 1st question.
```
[
    {
        type: 'select',
        name: 'anumber',
        message: 'Choose',
        choices: [
            { title: '1st', value: 1 },
            { title: '2nd', value: 2 }
        ],
        initial: 0
    },
    {
        type: (prev, values, prompt) => (prompt.name === 'anumber') ? 'number' : null,
        name: '2ndQuestion',
        message: 'second question',
    }

]
```

### Expected behavior
Prompt should present the 2nd question based on the question type function.

### System

- OS: MacOS 10.14.6
- Terminal: vs code terminal V1.36.0
- Node version: v12.7.0

**Comment by terkelg** [comment]
Thank you @vaffonso! Nice catch
