### ISSUE TITLE
Recommended way of testing `validate` outcome?

### ISSUE THREAD

**Issue by faustbrian** [terkelg/prompts#199]
I've recently started to write some tests for an application that uses prompts for its CLI but encountered an issue.

Simulating input is easy thanks to the `inject` method so getting to 100% coverage is fairly easy except for 1 issue, how would you test the `validate` outcome of prompt items?

For example I have a prompt that expects a value to be a number and when I run the CLI it properly outputs an error when I enter a string but during tests I with `inject` I can just add any value and the `validate` gets never triggered.

Is there currently any way to make prompts respect the validation rules specified in `validate`?

**Comment by terkelg** [comment]
Thank you for the issue – I think this relates to #197. Testing is something that needs improvement for sure.

**Comment by faustbrian** [comment]
Thinking if something as simple `prompts.inject([], false)` would be sufficient. Then internally we would do 2 things based on the second argument.

1. Treat the argument as `skipValidation` and pass it around.
2. If the value is `false` we do not skip validation, instead we throw an exception if we detect that the value is injected.

@terkelg What do you think about that approach? Would make failing validation easy to test with something like jest as `await expect(prompts()).rejects.toThrow()`.

**Comment by elliot-nelson** [comment]
I wonder if that actually gets you what you need in this case.  For example:

```
async functionUnderTest() {
    let result = await prompts({
        message: 'Enter a perfect square',
        type: 'number',
        name: 'square',
        validate: x => Math.sqrt(x) % 1 === 0
    });
    return result.square;
}
```

I think you can't really write a test for this.  If the user enters a non-square, `prompts` doesn't reject; it just keeps asking the user to enter a different number until they succeed, then it returns it.

What you really want to know is "will my validator function return false if the number isn't square".  The only way to really do that today is to split up your functions and unit test them separately, i.e.:

```
// write a unit test for this
function isPrime(value) {
    return Math.sqrt(value) % 1 === 0;
}

// ...
    type: 'number',
    validate: isPrime
```

I'm not sure how `prompts` could really support this, except by providing some kind of introspection layer.  For example, if you could "inject" the values `[34, 17, 36]` for `square`, and then later `expect(prompts.validations.square).toEqual([false, false, true]);` or something like that.
