### ISSUE TITLE
Remove "Page 1/1" from 'autocomplete' when there's only single page.

### ISSUE THREAD

**Issue by saurabhdaware** [terkelg/prompts#207]
If user is having lesser options in autocomplete which are going to be static throughout his application then I think it would be fine to not have `Page 1/1` written in the bottom.

Edit: I can give it a go if you want to remove it.

**Comment by bbernstein** [comment]
I have a pull ready that will remove pages entirely and instead have continuous scrolling. #230

**Comment by terkelg** [comment]
#230 is an even better solution 👍 Closing since this is merged into master now and will be a part of the next minor version. Thank you guys
