### ISSUE TITLE
Prompt with null type still executes choices logic

### ISSUE THREAD

**Issue by intel352** [terkelg/prompts#211]
### Describe the bug
Prompt with a `choices` property that is a function, still has it's `choices` function evaluated, despite `type` being evaluated to `null`.

### To Reproduce

1. Simplest example:
```
{
  type: true === false ? 'autocompleteMultiselect' : null,
  name: 'example',
  message: 'This config would still see it\'s choices function processed',
  choices: (prev, answers, question) => console.log('Choices evaluated here')
}
```

### Expected behavior
I would expect that once a prompt determines that it will not execute or be displayed, that the function evaluation would be halted for it's various properties, most explicitly properties that return a list of values or autocomplete suggestions. If this isn't halted, then whatever processing time would normally be incurred by the `choices` function will still be incurred, while nothing is printed on the screen.

As a workaround to this, the implementor can use the `question` param in the callback, to then check `question.type`, and exit early if it's set to a falsy value.

**Comment by DanielGibbsNZ** [comment]
I've noticed the same thing when using a function/lambda for the `message` property: if `type` is `null` I would expect `message` not to be evaluated.

**Comment by terkelg** [comment]
Thank you @intel352 and @DanielGibbsNZ. The prompt should not execute on `null`. Are you one of you interested in doing a PR?

**Comment by DanielGibbsNZ** [comment]
Sure. I've raised #217 which fixes this issue.
