### ISSUE TITLE
A `default` property in prompt obect

### ISSUE THREAD

**Issue by olstenlarck** [terkelg/prompts#22]
Heya! :hand: 

The thing is that there is the `initial` currently. But i believe it would be better the initial to be set in parens before the `›`. It's cool feature, and it can be used to set default values, but if user dont want the default he need to waste time in deleting it to set another. As about if we have `default` then it can be shown in `parens` same as `initial` (if initial not set) and if user like the default then just to click `enter`.

One more thing that i'm thinking about is `required` boolean prop to allow the question to be required or not. If required and not set then throw, end the stream or show message which is kinda related to the discussion in https://github.com/terkelg/prompts/issues/2#issuecomment-368684875 thread.

If not adding `required` then `validate` is good option too. [Use case.](https://github.com/tunnckoCore/gitcommit/blob/15d16c2a60bf41495204ddd926beb3756422f717/src/cli.js#L12-L35)

**Comment by olstenlarck** [comment]
done. :D

**Comment by terkelg** [comment]
I'll consider adding some visual feedback for initial values but it's very low priority at the moment. Fixing bugs and writing tests is the main focus now. I'll close this for now.
