### ISSUE TITLE
Select Prompt with horizontal and vertical choices

### ISSUE THREAD

**Issue by pke** [terkelg/prompts#224]
I wonder if its possible to implement a `select` that displays like this, where one can also select horizontally on option 1:

```bash
> [1.1] [1.2]
  [2]
  [3]
```

With this kind of choices: 

```js
{
 type: "select",
 choices: [["1.1","1.2"],"2","3"]
}
```

Maybe this is possible using a custom nested prompt?

**Comment by terkelg** [comment]
Thank you for the suggestion @pke. I think this could be a future prompt type for sure. I'm going to mark this as `enhancement` and close it for now. I want to keep focus on the next release of prompts which is going to make it even easier to make new prompt types in the future

**Comment by pke** [comment]
Looking forward to the new release.
