### ISSUE TITLE
number: value timer should have visual cue

### ISSUE THREAD

**Issue by elliot-nelson** [terkelg/prompts#228]
### Describe the bug
By design, the `number` field "resets" the current value after waiting 1 second.  That means if you continue typing, you start over and overwrite the number currently displayed.

This causes some confusing behavior, for example:

- *Validations* The user enters invalid value, then reads the resulting message.  They try again, and typing the new number overwrites the old one.  This number is also invalid, but the user has already read the error message, so they are much quicker -- their third attempt should work, but now the new number is appending instead of overwriting.  To the user, this difference in behavior appears as just buggy and inconsistent.

- *Code entry* If the field is a MFA token, phone number, one-time pass, etc. -- a number that might involve the user looking down to read the next set of numbers to enter -- it is essentially a race condition whether the user will continue to type the number they intend, or will overwrite the numbers they entered, making for a frustrating and confusing experience.

### Expected behavior
I'm not sure what the use case was, but I think the timing element should be removed.

1. In normal entry mode, typing additional numbers should always append.
2. After hitting ENTER, and failing validation, always reset (overwrite).

### Additional context

I've considered maybe for my example of things like keycodes and PINs, I should just be using a text field with a validator (maybe I'm using `number` type wrong).  I'd still be curious what the 1-second reset is "for".

**Comment by terkelg** [comment]
I think the timer provided for a good UX in some cases. Maybe this should be an option or,  as you suggest, maybe a text prompt + validator would be better in cases like this

**Comment by elliot-nelson** [comment]
I can accept that :).

I think if the "reset" is built in to this prompt type, a nice-to-have would be to somehow show the cursor resetting when it happens.

I'm not sure if you can move the cursor to the beginning of the text field, and then turn the cursor on?  Or perhaps keep the TTY cursor off and do a small manual animation to show that the cursor has reset.

**Comment by terkelg** [comment]
I'm adding this to the 3.0 milestone for now. Thank you
