### ISSUE TITLE
Autocomplete to support Tab (or add a notice in docs)

### ISSUE THREAD

**Issue by olstenlarck** [terkelg/prompts#23]
It seems that it not completes the word. But also, it's not a problem, because it is in the result when click enter - we can add notice for it in docs.

Example (i know for this question is more good the `select` but, yea, why not autocomplete [i dont like arrows ;d]).

```js
async function run() {
  const response = await prompts({
    type: 'autocomplete',
    name: 'type',
    message: 'What is the type of the change?',
    choices: [
      { title: 'fix' },
      { title: 'feat', value: 'feature' },
      { title: 'break' },
      { title: 'major' },
      { title: 'chore' },
    ],
  });

  console.log(response);
  // => { type: 'feature' }
}

run()
```

type `fe` and Enter. Result is correct anyway, but users has habits to click Tab to finish the word (i believe).

**Comment by terkelg** [comment]
This is low priority but I'm open for tab-completion if it can be done in very few lines of code.

**Comment by terkelg** [comment]
Closing for now. The autocomplete prompt highlights the selected item

**Comment by olstenlarck** [comment]
Even if not tab completion feature won't be implemented, there is still visual big that when click enter the selected item is not shown fully.

will screen it later

**Comment by olstenlarck** [comment]
Oh, cool. Seems it is somehow fixed. :)
