### ISSUE TITLE
Dynamically add prompts based on answers of previous questions

### ISSUE THREAD

**Issue by jcdietrich** [terkelg/prompts#239]
I would like to prompt for a number of players, then prompt for each player's age for instance.

How many players? 3
Player 1's age?
Player 2's age?
Player 3's age?

Is there a way to dynamically add to the prompt array based on some of the answers already provided?

Or perhaps a new type called prompt that would generate a subobject with the answers to all of the new questions?

```
const questions = [
    {
        type: 'number',
        name: 'players',
        message: 'Number of players?',
    },
    {
        type: 'prompt',
        name: 'ages',
        message: prev => {
            const empty = new Array(prev).fill({});
            const questions = empty.map((x, i) => ({
                type: 'number',
                name: `player${i+1}Age`,
                message: `Player ${i+1}'s Age?'`,
            }))
           return questions;
        }
    },
]
```

Output: 
```
{
  players: 2,
  ages: {
     player1Age: 23,
     player2Age: 34,
  },
}
```

**Comment by terkelg** [comment]
I usually create two prompts for this:

```js

const first = await prompts([...]);

// do logic with the answers

const second = await prompts([ ... ])
```

From a users perspective, this looks like on prompt chain

**Comment by jcdietrich** [comment]
That could work for me I guess... I have coded up something you can look at at https://github.com/terkelg/prompts/pull/240

**Comment by keenahn** [comment]
I accomplish this with multiple prompts.
