### ISSUE TITLE
Select prompt: Problems & more friendlier `initial`

### ISSUE THREAD

**Issue by olstenlarck** [terkelg/prompts#24]
One more issue, sorry but.. :laughing: 

I understand that it is normal to be zero based, but is an exposed API, why we should think about it.

Btw, from here we can see one problem. Consider the example

```js
async function run() {
  const response = await prompts({
    type: 'select',
    name: 'type',
    message: 'What is the type of the change?',
    choices: [
      { title: 'Fixing a bug', value: 'fix' },
      { title: 'New feature', value: 'feat' },
      { title: 'Breaking change', value: 'major' },
      { title: 'Non code changes', value: 'chore' },
      { title: 'Documentation changes', value: 'docs' },
    ],
    initial: 3,
  });

  console.log(response);
  // => { type: 'chore' }
}

run()
```

then click Enter. The response is correct, it selects the fourth (cuz it is zero based, okey). But visually it is not selected when run the program - it stays on the `Fix a bug`. I'll record asciinema record. So you can see what i'm talking.

https://asciinema.org/a/166247 or
<a href="https://asciinema.org/a/166247" target="_blank"><img src="https://asciinema.org/a/166247.png" /></a>

**Comment by terkelg** [comment]
An exposed API for developers should always be zero based. The end user here is developers working with code that expect a zero based index.

**Comment by olstenlarck** [comment]
I'm agree on that, what about the another? When `initial` is set i believe that the arrow in the list should be there (in this case in the fourth item) and not always on the first one.
