### ISSUE TITLE
passing undefined to `inject` is not transform to the default value 

### ISSUE THREAD

**Issue by rluvaton** [terkelg/prompts#265]
### Describe the bug
I tried to test with the initial values by passing `undefined` to `inject` but it treats `undefined` as is and not as it should use the initial value

### To Reproduce
```js
const prompts = require('prompts');

const questions = [
    {
        type: 'text',
        name: 'value',
        message: 'What your OS',
        initial: 'Linux'
    },
    {
        type: 'number',
        name: 'age',
        message: 'How old are you?'
    }
];

(async () => {
    prompts.inject([undefined, 10]);
    const response = await prompts(questions);

    console.log(response);

    // => response => { value: undefined, age: 10 }
})();
```
### Expected behavior
I want that when I pass `undefined` it'll use the initial value.

In the above example, I want that `response` will equal `{ value: 'Linux', age: 10 }`

### System

- OS: Windows 10
- Terminal: cmd
- Node version: 13.1.0

### Additional context
- prompts: 2.3.2

**Comment by rluvaton** [comment]
@terkelg What do you think?

**Comment by terkelg** [comment]
I agree - `undefined` should result in the default value being used
