### ISSUE TITLE
💡 Web-like form functionality

### ISSUE THREAD

**Issue by brodybits** [terkelg/prompts#267]
### Is your feature request related to a problem?

The [`brodybits/react-native-module-init`](https://github.com/brodybits/react-native-module-init) and [`npm:generate-cordova-package`](https://www.npmjs.com/package/generate-cordova-package) tools suffer from poor & frustrating UX if the user makes a mistake and has to start over.

### Describe the solution you'd like

Enquirer does support the form functionality but seems to only be for text inputs: https://github.com/enquirer/enquirer#form-prompt

Some kind of web-like form functionality with support for input types such as text input, single choice, multiple choices, and perhaps yes/no confirm would really help improve the UX.

### Describe alternatives you've considered

- Do this in a plugin if plugin API is supported (#254)
- See if enquirer does this as I suggested in <https://github.com/enquirer/enquirer/issues/301>
- Make this as a plugin for enquirer
- Do this in a fork of prompts or enquirer, which I would really rather avoid

### Additional context

N/A

**Comment by terkelg** [comment]
Looks neat. I would like the next version of prompts to provide an API to make your own prompts. That would make it easy to make custom prompts like that 👍
