### ISSUE TITLE
Remove handling of CTRL+C

### ISSUE THREAD

**Issue by olstenlarck** [terkelg/prompts#27]
In most cases it is used to kill whole program and i'm pretty used to it. Don't want to be used as canceling questions.

Secondary issues: CTRL+Z and CTRL+X are not working too, so you literally don't have any chance to close the program earlier, except to CTRL+C until questions end, what if you have dozens (not my case)?

**Comment by terkelg** [comment]
Not sure what I think of this one. It only prevents your program from being killed while waiting for user input.

**Comment by olstenlarck** [comment]
Haha. If user want to kill it, let him kill it. Mostly everything uses Ctrl+C for kill, except copy-pasting but it's in rare cases.

**Comment by terkelg** [comment]
Alright. Let's make a poll (Click to vote)
[![](https://api.gh-polls.com/poll/01C7NC1JDKC6R4SXQMMQW246A8/Remove)](https://api.gh-polls.com/poll/01C7NC1JDKC6R4SXQMMQW246A8/Remove/vote)
[![](https://api.gh-polls.com/poll/01C7NC1JDKC6R4SXQMMQW246A8/Keep)](https://api.gh-polls.com/poll/01C7NC1JDKC6R4SXQMMQW246A8/Keep/vote)

**Comment by FoRVaiS** [comment]
Oh that poll is glitched... If a user goes back to 'previous page', it increments the counter... I'm also pretty sure i can click it again to stack votes... :) -1 vote on 'Remove'

**Comment by terkelg** [comment]
Right, thanks for letting me know That means it's 1/1 now

**Comment by olstenlarck** [comment]
> -1 vote on 'Remove'

@FoRVaiS what you mean by voting `-1`? The proof why it should be removed is in your native expectation/assumption to click CTRL+C (seen in your issues) to exit a program, when you encounter something strange.

**Comment by FoRVaiS** [comment]
@olstenlarck Oh, the -1 was because i voted twice by accident.

**Comment by olstenlarck** [comment]
I don't see any problems with the poll. I can't vote more than once and tried your way too - no glitches.

**Comment by FoRVaiS** [comment]
Then i guess someone had voted immediately after i did. I guess score remains 3 to 1 :P

**Comment by lukeed** [comment]
Sorry for silence -- I'll spin something up today to see how it feels.

**Comment by lukeed** [comment]
It's definitely smooth to _have_ the ability to "skip" prompts. However, I could see this being really unexpected for the majority of cases.

I would think that the best bet to make this configurable, with immediate exits being the default.

The current behavior could be configured globally (within `prompts()`) or on a per-prompt basis (via a `optional: boolean` key).

**Comment by terkelg** [comment]
Agree. Let's make this optional. What makes most sense global or per-prompt basis?

**Comment by FoRVaiS** [comment]
Default to CTRL+C to terminate program on a per-prompt basis

**Comment by terkelg** [comment]
Thanks to @lukeed recent refactor this shouldn't be that hard to implement. Still require changes to all base elements tho.

**Comment by lukeed** [comment]
On second thought, I think they're two separate features. 

The global one can be implemented on the main handler. Right now, the `onCancel` is called only when cancels are received. There aren't any errors anymore. So something like this 

```js
} catch (err) {
  quit = !opts.greedy || onCancel(prompt)
}
```

**Comment by terkelg** [comment]
I like the `greedy` naming!

**Comment by olstenlarck** [comment]
Don't why there should be tons of keystrokes - currently it is possible to skip question with Ctrl+D and Escape, it's pretty enough and expected. Just document it and don't do anything for the Ctrl+C. :)

**Comment by terkelg** [comment]
Each individual prompt element can be quitted. The `abort` action can be activated in a few different ways: <kbd>ctrl</kbd>+<kbd>c</kbd>, <kbd>ctr+</kbd>+<kbd>d</kbd>,  <kbd>abort</kbd> and <kbd>esc</kbd> ([action.js](https://github.com/terkelg/prompts/blob/master/lib/util/action.js)). This makes sense when you use them on their own and pretty much the expected behaviour for all CLIs. 

The question is what happens when your in a question loop. I guess the `greedy` option is the way to go. But why would you ever "skip" a question anyway - wouldn't that just be a prompt with a default value then?

One thins is sure tho. We'll always have to do some logic on `abort` to clean up. We just can't ignore it.

**Comment by olstenlarck** [comment]
> why would you ever "skip" a question anyway - wouldn't that just be a prompt with a default value then? 

exactly.

> The abort action can be activated in a few different ways: ctrl+c, ctr++d, abort and esc (action.js).

exactly. it is too much and I dont see why should handle ctrl+c. The default behavior for this keystroke for most CLIs is to quit the whole program, no matter what it does.

And here are not talking to remove some feature and dont allow end users to abort some question - they still will be able to do it. But would allow others to quit the whole program, as they may expect. And you already seen one such user, and in future there will be more and more issues about that. Currently, they literally cant do it.

**Comment by olstenlarck** [comment]
Dont why implementer of such CLI should think about greedy option at all.

And also it's not breaking change.

**Comment by terkelg** [comment]
Prompts run as a part of other CLI programs. I don't want to have people accidentally quit the main program when they try to abort prompts. I agree `abort` should quit the prompt and prompt loop and don't need any options. But it should abort and return control to the program. It's up to that program to decide what to do. Worst case you'll have to hit `ctrl`+`c` twice when you're in a prompt and want to quit the whole thing.

**Comment by olstenlarck** [comment]
I'm okey with double Ctrl+C.

**Comment by kjbrum** [comment]
Am I understanding correctly that there isn't any way to know if a user cancelled the prompts by hitting `ctrl + c`?

**Comment by olstenlarck** [comment]
@kjbrum you can. With the `onAbort` i believe or `onCancel`.

The whole thing was that i still don't understand why we should think for "greedy" option at all as implementers of such CLIs. But anyway.

**Comment by giacomocerquone** [comment]
This is completely unnatural if you ask me, and believe it or not but I arrived in this issue voluntarily, because of this strange, at least to me, ctrl+c behaviour (and double ctrl+c doesn't seem to work to me).
For instance if I want to close the cli after a ctrl+c has been pressed, I've to check the empty answer and call process.exit(1)

At least let's write it in the docs

**Comment by llirikkk** [comment]
> This is completely unnatural if you ask me, and believe it or not but I arrived in this issue voluntarily, because of this strange, at least to me, ctrl+c behaviour (and double ctrl+c doesn't seem to work to me).
> For instance if I want to close the cli after a ctrl+c has been pressed, I've to check the empty answer and call process.exit(1)
> 
> At least let's write it in the docs

I had to do the same trick (check if result is not empty and then exit the process with 130 code). But having to do this for every prompt was really tedious. Had to switch to Inquirer.js only because of this issue..

**Comment by tunnckoCore** [comment]
> @llirikkk: But having to do this for every prompt was really tedious. Had to switch to Inquirer.js only because of this issue..

You can always make a wrapper around the onSubmit or wherever above that snippet above is. 

Yea, it's not the best way and definitely such workaround aren't _THE WAY_, but is (even better) possibility than switching to bigger and slower Inquirer. Or at least you can try `enquirer` if you want so, which is mega configurable too and zero-dep.

Seeing @terkelg marked it as v3... that will be great! :)

**Comment by joeythomaschaske** [comment]
This makes debugging scripts an absolute pain. It doesn't help prompts doesn't work with the vscode debugger.
