### ISSUE TITLE
🎉 usage in the React ecosphere

### ISSUE THREAD

**Issue by brodybits** [terkelg/prompts#284]
FYI it looks like `prompts` is now used in `create-react-app`: 

- https://github.com/facebook/create-react-app/pull/10083
- https://twitter.com/Baconbrix/status/1330852677325119493

and maybe coming into the React Native CLI: https://github.com/react-native-community/cli/pull/1010

**Comment by brentvatne** [comment]
also in expo-cli https://github.com/expo/expo-cli/ :)

**Comment by EvanBacon** [comment]
And in [`create-react-native-app`](https://github.com/expo/create-react-native-app)! 😁

**Comment by terkelg** [comment]
That's amazing! 🎉  It wouldn't be possible without you guys

**Comment by brodybits** [comment]
https://github.com/storybookjs/storybook/pull/13225 - merged & published in `next` - seems to be insp;ired by @EvanBacon!
