### ISSUE TITLE
Add format property

### ISSUE THREAD

**Issue by simonepri** [terkelg/prompts#3]
Proposal to add a `format` property:

> filter: (Function || Async Function) Receive the user input and return the formatted value to be used inside the program.
The value returned will be added to the answers.

API Usage Example::

```js
  format: confirm => !confirm
```

**Comment by lukeed** [comment]
Agreed, but should be `format` IMO. Otherwise sounds like logic to specify which prompts to display, or something like that.

**Comment by lukeed** [comment]
That or merge this behavior into `onSubmit`

**Comment by simonepri** [comment]
Yeah I agree with `format` instead of `filter`

**Comment by terkelg** [comment]
Nice 💯. Let's implement this

**Comment by terkelg** [comment]
Please checkout the [implementation here](https://github.com/terkelg/prompts/blob/format/lib/prompt.js#L35).

Should the `onSubmit` function receive the raw value or the formatted value?

I also pass the current `answers` object as a second param in case you want to format based on previous values.

**Comment by lukeed** [comment]
I would pass the formatted answer to `onSubmit`

```js
answers[prompt.name] = answer = prompt.format ? prompt.format(answer, answers) : answer;
```

I also don't think there's a need for async formatters, but might as well since we're inside an async function.

**Comment by terkelg** [comment]
Cool! Thanks guys. Added in #7

**Comment by simonepri** [comment]
@terkelg 
It shouldn't be:
```js
answers[prompt.name] = answer = prompt.format ? await prompt.format(answer, answers) : answer;
```
??

**Comment by terkelg** [comment]
@simonepri I guess. But I think we have to redo this anyway. The prompt level `onSubmit` and `onCancel` clashes a bit with the format function  (#43)

**Comment by terkelg** [comment]
@simonepri yeah I guess you're right. Let's make it async.
