### ISSUE TITLE
prompts messing stdin after being used

### ISSUE THREAD

**Issue by SrBrahma** [terkelg/prompts#312]
### Describe the bug
In my terminal program, I've added a "Press any key to continue" using [this](https://stackoverflow.com/a/49959557/10247962). However, I found out it was not working after using prompts. The "Press any key" wouldn't read any input, and would just continue by itself after some seconds passed.

### To Reproduce

```ts

export const keypress = (): Promise<void> => {
  // process.stdin.removeAllListeners(); // I tried this. didnt work.
  process.stdin.setRawMode(true);
  return new Promise<void>(resolve => process.stdin.once('data', () => {
    process.stdin.setRawMode(false);
    resolve();
  }));
};

(async () => {

  console.log('Press any key to continue...');
  await keypress(); // This will work properly

  const { username, password } = await prompts([
    {
      message: 'Enter the username',
      type: 'text',
      name: 'username',
    }, {
      message: 'Enter the password',
      type: 'password',
      name: 'password',
    },
  ]);

  console.log('Press any key to continue...');
  await keypress(); // This won't work properly. Not input will be taken, will after some seconds continue by itself.

})()
```

### Expected behavior
prompts should clean its changes to stdin after being used.

### System

- OS: Ubuntu 20.10
- Terminal: zsh
- Node version: 14.15.4
- prompts version: 2.4.1

**Comment by SrBrahma** [comment]
@terkelg can you please take a look at it?

**Comment by ui3o** [comment]
The finding is valid. I could also reproduce on:

- OS: Arch
- Shell: zsh
- Node version: v16.0.0
- prompts version: 2.4.1

But this issue is not related for prompst only, because the mentioned code also not work properly like this:
```
const keypress = () => {
    process.stdin.setRawMode(true);
    return new Promise(resolve => process.stdin.once('data', () => {
        process.stdin.setRawMode(false);
        resolve();
    }));
};

(async () => {
    console.log('Press any key to continue...');
    await keypress();
    console.log('Press any key to continue...');
    await keypress();
})()
```
The result for me, it will no hungup the code running. **The program never stop.**

# Solution

- Use prompts original keypress handle method. This works for me:

```
const keypress = () => {
    return new Promise(resolve => {
        const rl = readline.createInterface({ input: process.stdin, escapeCodeTimeout: 50 });
        readline.emitKeypressEvents(process.stdin, rl);
        process.stdin.setRawMode(true);
        process.stdin.resume();
        const listener = (key) => {
            console.log('ke', key)
            process.stdin.removeListener('keypress', listener)
            process.stdin.setRawMode(false);
            rl.close();
            resolve();
        }
        process.stdin.on('keypress', listener)
    });
};

(async () => {
    console.log('Press any key to continue...');
    await keypress();
    const { username, password } = await prompts([
        {
            message: 'Enter the username',
            type: 'text',
            name: 'username',
        }, {
            message: 'Enter the password',
            type: 'password',
            name: 'password',
        },
    ]);
    console.log('Press any key to continue...');
    await keypress();
})()
```

**Comment by SrBrahma** [comment]
You are also using zsh. Maybe it's the problem? Tomorrow I will test the
issue in the bash and also your solution. Thanks!

Em sex, 14 de mai de 2021 20:56, ui3o ***@***.***> escreveu:

**Comment by ui3o** [comment]
The issue is not related to the shell. 

I tested in bash and fish also. The issue is related to how nodejs handle the key events. You can find the solution above.

**Comment by SrBrahma** [comment]
Works like a charm here, thanks! I just needed that fixed to finish a quick project. I am closing this issue for the given workaround.
