### ISSUE TITLE
Cannot use select on Git bash

### ISSUE THREAD

**Issue by lie5860** [terkelg/prompts#337]
### Describe the bug
If I set an option of type select。
It will not be able to be selected
### To Reproduce

1.npm init @vitejs/app

### Expected behavior
Can use numbers and carriage returns to select.
like inquirer
[https://github.com/SBoudrias/Inquirer.js](url)
### System

- OS: [win10]
- Terminal: [gitbash]
- Node version: v14.18.1

### Additional context
This problem does not exist in cmd.exe.
emmm,It could be a requirement?

**Comment by pierreavn** [comment]
+1 Same issue on Git Bash with another project :/

**Comment by mato-a** [comment]
+1 Same issue using Git Bash on Win 10, node v17.8.0, project svelte: `npm init svelte my-app`

**Comment by mato-a** [comment]
Hi there,

I have found a workaround - executing the command in Visual Studio Code using git bash terminal works. Using standalone git bash fails.

This issue seems to be related to https://github.com/terkelg/prompts/issues/303
