### ISSUE TITLE
Prompts doesn't work in global packages with Git Bash or Windows CMD

### ISSUE THREAD

**Issue by FoRVaiS** [terkelg/prompts#35]
**OS:** Windows 7 Ultimate 64-bit SP1
**Node**: v9.5.0
**Prompts**: v0.1.4

Whenever I press 'enter' on a `prompts.select` or `prompts.text`, I get:
```shell
TypeError: this.in.setRawMode is not a function
    at TextPrompt.close (C:\projects\_PLAYGROUND\PromptsDontWorkGlobal\node_modules\prompts\lib\elements\prompt.js:39:15)
    at TextPrompt.submit (C:\projects\_PLAYGROUND\PromptsDontWorkGlobal\node_modules\prompts\lib\elements\text.js:50:10)
    at Socket.keypress (C:\projects\_PLAYGROUND\PromptsDontWorkGlobal\node_modules\prompts\lib\elements\prompt.js:30:16)
    at Socket.emit (events.js:160:13)
    at emitKeys (internal/readline.js:420:14)
    at emitKeys.next (<anonymous>)
    at Socket.onData (readline.js:1021:36)
    at Socket.emit (events.js:165:20)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
```

**CODE:**
```javascript
#!/usr/bin/env node

const prompts = require('prompts');

const presets = {
    'App': 'OTHERDATA',
    '(Express|EJS)': 'OTHERDATA',
    'Webpack-Dev-Server + (Webpack|ES6-BABEL|SCSS)': 'OTHERDATA',
    'React + Webpack-Dev-Server + (Webpack|ES6-BABEL)': 'OTHERDATA',
    'React + Redux + Webpack-Dev-Server + (Webpack|ES6-BABEL)': 'OTHERDATA'
};

(async () => {
    const { answer } = await prompts({
        type: 'text',
        name: 'answer',
        message: 'Hello FöRVaiS'
    });

    console.log(answer);

    const { data: [, data] } = await prompts({
        type: 'select',
        name: 'data',
        message: 'Select a preset from this list',
        choices: Object.entries(presets).map(preset => ({ title: preset[0], value: preset })),
        initial: 0
    });

    console.log(data);
})();
```

**Comment by olstenlarck** [comment]
What you mean with "in global packages"? I can't got it. ;]

**Comment by FoRVaiS** [comment]
Sorry, i was just about to update my post regarding that.

I've published the sample code in a private repository and installed globally: `npm install -g local-prompts-global`. 

The global package also has a bin command:
```json
"bin": {
    "prompts-test": "index.js"
 }
```
Running `prompts-test` will result in a failing prompts application

**Comment by olstenlarck** [comment]
Huh. And locally works?

I have strong feeling, looking on the stack trace, that it may be because #19

**Comment by olstenlarck** [comment]
Actually it isn't because of #19.

Possible fix would be

```js
this.in.setRawMode = this.in.isTTY ? this.in.setRawMode : () => {}
```

So we won't think for it in other places.

**Comment by FoRVaiS** [comment]
Using Visual Studio Code (VSC) Terminal, I can use Prompts perfectly:
![qug7ifv7sfqkb5-6g4stug](https://user-images.githubusercontent.com/1572440/36894708-233c218e-1dc1-11e8-9997-74890f4052cf.png)

**Comment by olstenlarck** [comment]
Can you try to replace this line https://github.com/terkelg/prompts/blob/b6126d37b7cbcd04b36917d948c989962af783db/lib/elements/prompt.js#L39

with

```js
      if (this.in.isTTY) {
        this.in.setRawMode(false);
      }
```

so we can verify more faster if it is only that thing. Because it not make sense to me since it works locally, but this bug is seen in other big projects too.

**Comment by FoRVaiS** [comment]
I no longer get the exception. 
`Prompts.text` responds correctly and then duplicates its line.
`Prompts.select` remains un(_scrollable_)?
At the end, the application hangs, unable to kill the process.

![demo](https://user-images.githubusercontent.com/1572440/36895248-21b78432-1dc3-11e8-97f2-3f55a3196f57.gif)

**Comment by olstenlarck** [comment]
Ah. Okey, thanks! We can continue on #36 then.

> CTRL+Z and CTRL+C.

It's another problem - #27

**Comment by olstenlarck** [comment]
Sorry for bothering you, but.. What about adding 

```js
      else {
        this.clear()
      }
```

Strongly believe that i would fix the problem with double lines, because `this.clear` is available after the `this.render` call, which in turn is called before the `this.close()` from the `submit()`.

**Comment by FoRVaiS** [comment]
I've already shut my computer off, I'll definitely try this tomorrow.

**Comment by olstenlarck** [comment]
Okey thanks anyway! :bee:  It's not comfortable in such situations when no tests and/or Windows specific things. Also, it's a bit tricky to test CLI prompts :D

**Comment by terkelg** [comment]
Right. So the issue is down to `prompts.select` not being scrollable on windows?

**Comment by FoRVaiS** [comment]
The only two functional issues I have come across so far is 

1. Unscrollable `prompts.select`
2. Application hanging

Issue 2 might be related to a hanging stdin but my experience on I/O is extremely limited so I could be very wrong :X
