### ISSUE TITLE
Deno support

### ISSUE THREAD

**Issue by DeeGeeMan** [terkelg/prompts#350]
Any plans to support the [Deno](https://deno.land) platform?

[Skypack CDN](https://www.skypack.dev/view/prompts)
![Screen Shot 2022-01-07 at 7 47 11 AM](https://user-images.githubusercontent.com/21670040/148546298-bd821496-7776-49a3-b982-34bb41c24ce1.png)

**Comment by Kreijstal** [comment]
any support for browser?

**Comment by terkelg** [comment]
Prompts won't be able to support the browser since it's a CLI

**Comment by TehBrian** [comment]
any update regarding this issue? prompts.js is lovely, and it'd be great if it were compatible with deno. thanks :)
