### ISSUE TITLE
Multi select with autocomplete?

### ISSUE THREAD

**Issue by simonwjackson** [terkelg/prompts#37]
Can this be implemented?

**Comment by terkelg** [comment]
It sure can. That being said I'll close this feature request for now since there's more important work right now than implementing new prompts/features for prompts

**Comment by armand1m** [comment]
Well, I'm needing this now :P there is any way to use this feature now with the current code? Or we need to hardcode this feature into this package?

**Comment by terkelg** [comment]
The code for auto complete and multi-select is already there. You can try to build the prompt. I'm open to PR. Just don't have the time to build it myself right now.
