### ISSUE TITLE
Consider including TypeScript declaration files

### ISSUE THREAD

**Issue by joeykilpatrick** [terkelg/prompts#377]
It's slightly inconvenient to have to have to separately install the `@types/prompts` package when using TypeScript with this library. That package has 288,624 weekly downloads, so there's a significant portion of this library's users who are using TypeScript.

DefinitelyTyped has [a long history](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/13364) of deprecating their packages when library owners are willing to include the declaration files directly in their package. The types for this package have [7 credited contributors](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/prompts/index.d.ts) to date. I'm proposing moving those declaration files here. I'm not suggesting rewriting any of the library in TypeScript, just including the `.d.ts` files.

Here's a recent issue for a type fix: #372 

Pros:
- Users no longer need to separately install `@types/prompts`
- Types can be kept in-sync with any new features without separate pull requests to DefinitelyTyped
- Tests in this repo can be written in TypeScript if that is wanted

@terkelg

**Comment by terkelg** [comment]
Let's include the types. Eventually I want to write a new version of prompts and that will be all TypeScript. For now we can include the types in the repo 👍
