### ISSUE TITLE
How to cancel these unnecessary logs

### ISSUE THREAD

**Issue by baiwusanyu-c** [terkelg/prompts#389]
### Describe the bug
When I make multiple selections, the console will output these logs. It looks terrible. I don’t want to display these. Is there any way to make it not display?

### To Reproduce

<img width="690" alt="微信截图_20230217102951" src="https://user-images.githubusercontent.com/32354856/219538774-011c2d50-fe86-481c-8be0-036ed973d930.png">

**Comment by joeykilpatrick** [comment]
Can you share the code for your prompt?

**Comment by baiwusanyu-c** [comment]
````
import prompts from 'prompts'

export const createRepoOption = (list: string[]) => {
  const handler = (item: string) => {
    return { title: item, value: item }
  }
  return [{
    type: 'multiselect',
    name: 'prSelect',
    message: 'Please select the PR that needs to be updated',
    optionsPerPage: 20,
    choices: list.map(handler),
  }] as unknown as prompts.PromptObject[]
}

export const promptsRun = async(option: prompts.PromptObject[]) => {
  const res = await prompts(option, {
    onCancel: () => {
      console.log('info', 'Operation cancel')
      process.exit()
    },
  })
  return { ...res }
}

promptsRun(createRepoOption(['foo', 'bar']))
````

![image](https://user-images.githubusercontent.com/32354856/219540330-2f26eab7-e241-4718-af98-55b60263d1cd.png)

**Comment by baiwusanyu-c** [comment]
I don't want to output the marked part of the red box, because when my data is complex, this log will become very ugly as I said at the beginning

**Comment by vkorni97** [comment]
I had the same problem, but I have a solution. Maybe not the best solution but overwrite renderDoneOrInstructions function with your own function.

```

 type: (prev) => (prev ? null : "multiselect"),
 name: "list",
 message: `Chose files to resync:`,
 choices: list.map((f) => {
     return { title: f.name, value: f };
 }),
 onRender() {
     if (this.firstRender) {
        this.renderDoneOrInstructions = customMultiselectRender;
     }
 },
```
```

export function customMultiselectRender() {
  if (this.done) {
    return `${color.grey(this.value.filter((e) => e.selected).length)} selected item`;
  }

  const output = [color.gray(this.hint), this.renderInstructions()];

  if (this.value[this.cursor].disabled) {
    output.push(color.yellow(this.warn));
  }
  return output.join(" ");
}

```

**Comment by baiwusanyu-c** [comment]
> I had the same problem, but I have a solution. Maybe not the best solution but overwrite renderDoneOrInstructions function with your own function.
> 
> ```
> 
>  type: (prev) => (prev ? null : "multiselect"),
>  name: "list",
>  message: `Chose files to resync:`,
>  choices: list.map((f) => {
>      return { title: f.name, value: f };
>  }),
>  onRender() {
>      if (this.firstRender) {
>         this.renderDoneOrInstructions = customMultiselectRender;
>      }
>  },
> ```
> 
> ```
> 
> import color from "kleur";
> 
> export function customMultiselectRender() {
>   if (this.done) {
>     return `${color.grey(this.value.filter((e) => e.selected).length)} selected item`;
>   }
> 
>   const output = [color.gray(this.hint), this.renderInstructions()];
> 
>   if (this.value[this.cursor].disabled) {
>     output.push(color.yellow(this.warn));
>   }
>   return output.join(" ");
> }
> ```
> 
> OR
> 
> ```
> 
>  type: (prev) => (prev ? null : "multiselect"),
>  name: "list",
>  message: `Chose files to resync:`,
>  choices: list.map((f) => {
>      return { title: f.name, value: f };
>  }),
>  onRender(kleur) {
>      if (this.firstRender) {
>         this.renderDoneOrInstructions = function() {
>             if (this.done) {
>                 return `${kleur.grey(this.value.filter((e) => e.selected).length)} selected item`;
>             }
> 
>             const output = [kleur.gray(this.hint), this.renderInstructions()];
> 
>             if (this.value[this.cursor].disabled) {
>                output.push(kleur.yellow(this.warn));
>             }
>             return output.join(" ");
>         };
>      }
>  },
> ```

thank your solution !
