### ISSUE TITLE
Default Value

### ISSUE THREAD

**Issue by gavinhenderson** [terkelg/prompts#47]
I was thinking there could be an option to allow for default values. I was thinking this could be implemented in a similar way to NPM does it, for example when you do

```
> npm init
.
.
.
> entrypoint (index.js): 
```

The default option is picked when no option is supplied. I am happy to work on this issue if it is something that you think should be added.

**Comment by lukeed** [comment]
Hey~! Not sure if you've seen this yet, but we've have similar discussions in #22 and #40. Is this something different?

**Comment by gavinhenderson** [comment]
@lukeed #22 Is more what I was meaning. Noticed it was closed as it low priority, if i were to implement this would the PR be accepted?

**Comment by terkelg** [comment]
Yes, I'm always open to PRs!

**Comment by lukeed** [comment]
Okay, gotcha, sounds good. 👍

I was about to suggest that you could use `inject()` in the meantime, but I forgot it immediately resolves/skips the prompt 😆
