### ISSUE TITLE
multiselect stalls

### ISSUE THREAD

**Issue by selfagency** [terkelg/prompts#48]
single select prompts and text prompts are working fine for me, but when i try to use a multiselect, the process just stalls out until i hit ctrl-c. then i see then next prompt in line after the multiselect before exiting.

```
✔ Deploy last commit? › no
✔ Rebuild assets? › yes
✔ Release type? › patch
✖ Flush cache? › yes
```

there should be a "select deployment targets" before that "flush cache." here's my object.

```
async function targets () {
  d.t = await prompts({
    type: 'multiselect',
    messages: 'Select deployment targets:',
    choices: [
      { title: 'dev', value: 'nylon-dev', selected: true },
      { title: 'staging', value: 'nylon-staging' },
      { title: 'production', value: 'nylon-production' }
    ],
    max: 3
  })
    .then(() => {
      return Promise.resolve()
    })
}
```

**Comment by selfagency** [comment]
never mind i caught my error

**Comment by terkelg** [comment]
Feel free to write it here in case other people makes the same mistake.

**Comment by selfagency** [comment]
i wrote `messages` instead of `message`.

however, i think it might be helpful to have an error that says 'unknown parameter: messages' or something because the unhandled rejection error is useless.
