### ISSUE TITLE
Cannot use a function for `message` since 0.1.5

### ISSUE THREAD

**Issue by skvale** [terkelg/prompts#57]
`0.1.4` was the last version I could do
```
{
  type: 'autocomplete',
  message: (prev, values) => `something with ${ prev } or ${ values.something }`,
  choices: [{ title: 'title' }]
}
```

Since 0.1.5 I get:
```
UnhandledPromiseRejectionWarning: Error: prompt message is required
    at prompt (node_modules/prompts/lib/index.js:29:13)
```

Either the code should allow functions, or the Readme should not define prompt objects as:
```
{
  type: String || Function,
  name: String || Function,
  message: String || Function,
  initial: String || Function || Async Function
  format: Function || Async Function,
  onState: Function
}
```

**Comment by terkelg** [comment]
Hi @skvale. Thanks for reporting! Have you tried the latest version. Had similar issue here #53

**Comment by terkelg** [comment]
@lukeed I'm pretty sure this should be moved under the for loop that invoke dynamic properties right? `message` could be a function
```js
    if (MAP[name] !== void 0) {
      answers[name] = MAP[name];
      delete MAP[name];
      continue; // take val & run
    }

    if (typeof question.message !== 'string') {
      throw new Error('prompt message is required');
    }
```

**Comment by skvale** [comment]
Yeah, I was just going to say that.

I created a PR that does that.  https://github.com/terkelg/prompts/pull/58

I moved the the `inject` check so I could write a test for it.

**Comment by terkelg** [comment]
Thanks! I'll have a look tonight when I get home
