### ISSUE TITLE
How to scroll the autocomplete?

### ISSUE THREAD

**Issue by oskarrough** [terkelg/prompts#62]
Hi, is it possible to scroll through autocomplete results somehow?

When you're at the last or first item, I expected up/down to page through the results. Search works great though, super fast here.

**Comment by terkelg** [comment]
Type to filter the list and then use `up/down` to navigate. Use `tab` to cycle the result. Hit `enter` to select the highlighted item below the prompt.

**Comment by oskarrough** [comment]
Thank you. But if there are more than ten results to your filter, how do you see or navigate to them? 

For instance, when you press `down` on the last result, shouldn't it continue to show the sixth result and so forth?

**Comment by terkelg** [comment]
It's not a scrolling list at the moment - it only show results as you type

**Comment by terkelg** [comment]
I'll consider adding a scrolling list in the future
