### ISSUE TITLE
Support node 6

### ISSUE THREAD

**Issue by ranyitz** [terkelg/prompts#64]
Some projects still support node 6.

My use case is that I want to use prompts in https://github.com/facebook/jest/pull/6442

The solution for that could be fairly easy:
1. Transpile the code using babel to `dist`
2. Create a main file that will route between `dist/index.js` and `lib/index.js` according to the user's node version.
3. Add another travis run using node 6.

It shouldn't interfere with the development, and there will be no performance change for users that use `node > 8`.

Let me know your thoughts.

**Comment by terkelg** [comment]
Sounds good to me. Do you have time to make a PR? It can be combined with #66. What do you think @lukeed? I just want the simplest possible build step to keep.

**Comment by ranyitz** [comment]
@terkelg Thanks! ❤️ 

I've added this PR #67 

The build step is simple, just run `npm run build` which will only need to happen on CI. If you're publishing from your machine, just make sure to build before that, so the users will get an updated `dist`.
