### ISSUE TITLE
type: 'number' does not allow 0 value

### ISSUE THREAD

**Issue by acarnwath** [terkelg/prompts#69]
When I provide an initial value of something other than 0, 1 for example, I am not able to override that initial value when I provide 0 as a response.

I believe I have tracked this down to this section in lib/elements/number.js:
```
submit() {
    this.value = this.value || this.initial;
```

My test:
```
    var response = await prompts( [{
        type: 'number',
        name: 'test',
        message: 'Try providing 0',
        initial: 1,
        format: val => {
            return parseInt( val, 10 );
        }
    });

    console.log(response.test);
```

**Comment by terkelg** [comment]
Thanks Allison! I'll have a look at it when I have time. Feel free to do a PR if you're keen on helping out
