### ISSUE TITLE
Arrow keys not working for the "select" prompt type

### ISSUE THREAD

**Issue by DrunkenPoney** [terkelg/prompts#75]
Pressing the arrow keys to change the selected value in a prompt of type _select_ does not work visually. The initial value remains the one selected / colored. Though, when I press enter/return it does not necessarily return the initial value. In other words, pressing the arrow keys changes the selected value but does not change the highlighted line in console / terminal.

<hr>

 **Edit:**
Arrow keys work in a DOS terminal but not in bash

**Comment by terkelg** [comment]
Thanks for reporting the issue. weird, I can't reproduce this in bash

**Comment by DrunkenPoney** [comment]
I think it's cause I was using a **mintty** bash terminal. 😊

**Comment by DrunkenPoney** [comment]
I think it's cause I was using a **mintty** bash terminal. 😊

**Comment by terkelg** [comment]
No biggie. I'll close the issue for now
