### ISSUE TITLE
TypeScript error when prompt is used

### ISSUE THREAD

**Issue by DanielRuf** [terkelg/prompts#77]
`prompt` seems to be a reserved word and throws an error when compiling a TypeScript file.

In this case we have to use `prompts`.

**Comment by terkelg** [comment]
Thanks for reporting this issue. I don't use TypeScript myself. Is it something you can fix?
There's a discussion about TypeScript here: https://github.com/terkelg/prompts/issues/12

**Comment by DanielRuf** [comment]
I guess we just have to change the docs and examples a bit to prevent such conflicts.

I will check this.

**Comment by terkelg** [comment]
Related to #12
