### ISSUE TITLE
How can I use prompts without a transpilation step?

### ISSUE THREAD

**Issue by bnb** [terkelg/prompts#82]
Currently the example.js file uses top level await and ESM, which aren't supported without transpilation in Node.js. 

I could be misunderstanding, but I'd ❤️ to use Prompts. Curious if there's currently a way to do it without transpiling?

**Comment by terkelg** [comment]
`async`/`await` is available in Node v7.6 and above. Prompts only use the transpiled version [if needed](https://github.com/terkelg/prompts/blob/master/index.js).

The example file is just for demonstration purpose only and not being transpiled. It's easy to convert to promises though.

**Comment by bnb** [comment]
Ah, gotcha. Apologies for my unfamiliarity with async/await and promises.

I suppose I assumed this was caused by trying to copy/paste the example into a file called `cli.js` (plus changing `const { prompt } = require('./');` to require the module) and running `cli.js`.

Suppose I'm doing something wrong, and don't necessarily expect support – mostly just curious what I am doing wrong if there is something 😅

```
/Users/tierney/GitHub/ncm-cli/cli.js:5
(async function(){
       ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by terkelg** [comment]
You have to remove `async/await` if you're node version is below 8. In that case you don't need the outer async function. Make sure to make the await call a promise too.

**Comment by bnb** [comment]
I'm using Node.js v10 😅
