### ISSUE TITLE
Allow `onSubmit` to be an async/Promise returning function

### ISSUE THREAD

**Issue by pvdlg** [terkelg/prompts#83]
Currently if `onSubmit` is an `async` or `Promise` returning function, prompt exit after the first question.

It would be useful to allow `onSubmit` to be an `async` or `Promise` returning function so we could do asynchronous things in between user answers.
That would allow for example to:
- Save current answers to recover later
- Send answers to a remote server
- Get derived values from a remote server, that could be used for following questions

Maybe it can be done by simply using https://github.com/sindresorhus/emittery instead of [EventEmitter](https://github.com/terkelg/prompts/blob/135250ce39dbb70b42ffc667f8a54fbeaff6c668/lib/elements/prompt.js#L5)?

**Comment by terkelg** [comment]
Hi @pvdlg.
I think this can be solved by making [this function](https://github.com/terkelg/prompts/blob/master/lib/prompts.js#L9) `async` and await the `onSubmit`. Can you try that? I'm open for a PR

**Comment by pvdlg** [comment]
Do you mean the `onAbort` function? It's a user defined function, what do you mean by making it `async`?

**Comment by terkelg** [comment]
Sorry it was a bit rushed. But yes, something like this
```JavaScript
function toPrompt(type, args, opts={}) {
  return new Promise((res, rej) => {
    const p = new el[type](args);
    const onAbort = opts.onAbort || noop;
    const onSubmit = opts.onSubmit || noop;
    p.on('state', args.onState || noop);
    p.on('submit', async x => res(await onSubmit(x)));
    p.on('abort', async x => rej(await onAbort(x)));
  });
}
```

**Comment by pvdlg** [comment]
Oh yes that's the idea but it currently doesn't work because  the `on` function of `p` (an `EventEmitter`) doesn't seems to support async functions.

**Comment by pvdlg** [comment]
After a bit more investigation awaiting the `onSubmit` function [here](https://github.com/terkelg/prompts/blob/135250ce39dbb70b42ffc667f8a54fbeaff6c668/lib/index.js#L52) works.

Awaiting `onSubmit` or `onAbort` in `toPrompt` has no effect. Is that expect? Does it make sense to you?

**Comment by terkelg** [comment]
Oh that's where we want to await. I see. Can you do a PR we can test?

**Comment by pvdlg** [comment]
Yes, I already opened it: #84

**Comment by terkelg** [comment]
Thanks! Will be a part of v1.1.0
