### ISSUE TITLE
Delete-Key yields 'undefined'

### ISSUE THREAD

**Issue by fabsenet** [terkelg/prompts#86]
I have a simple index.js with a single text prompt and when I press the DEL-key (not backspace!) the text becomes literally "undefined". I can then delete the u but nothing else.

index.js:
```js
var prompts = require("prompts");

async function main() {
  var prefix = await prompts({
    type: "text",
    name: "prefix",
    message: "Prefix!"
    //    initial: "muh"
  });
  console.log(prefix);
}

main();
```

shell:
```powershell
PS C:\test\muh> node .\index.js
√ Prefix! ... undefined
{ prefix: 'undefined' }
PS C:\test\muh>
```
I pressed DEL, then ENTER

Expected behavior: DEL changes nothing or deletes the character which is right from the cursor (this does also not work!)

Versions:
node: v10.3.0
npm: 6.1.0
prompts: 1.0.0
Windows Server 2016 Datacenter (azure vm)

**Comment by terkelg** [comment]
Thanks for reporting the issue!
I'll have a look at this.

**Comment by DrunkenPoney** [comment]
It's not only on powershell

**Comment by terkelg** [comment]
I'll have a look at this when I have time. Have you looked into this @DrunkenPoney?

**Comment by DrunkenPoney** [comment]
@terkelg Yes and I'm about to create a PR
