### ISSUE TITLE
Dynamic Choices?

### ISSUE THREAD

**Issue by lukeed** [terkelg/prompts#88]
It seems like, if for no other reason than consistency, the `choices` key on selects & multiselects can/should accept a function that receives all answer and the immediately preceding answer before it in the chain.

The use case is to dynamically show/hide choices based on the value/existence of a previous answer.

With [PWA](https://github.com/lukeed/pwa), for example, I only want to show `TSLint` as a choice in the "Linter or Formatter" list if `TypeScript` had been selected previously in the "Features" section. There are also some other instances where this would come in handy, but that's the simplest one to explain.

**Comment by DrunkenPoney** [comment]
I don't understand... Isn't it what already that? I mean actually I can pass a function to choices and it works just fine. The function receives the previous answer, an object containing all the previous answers and the current prompt object as arguments in this order.
With these arguments you can easily get the value of a previous answer, so I'm not sure if I understand what you want exactly.

**Comment by lukeed** [comment]
Hmm.. I know I was rushed at the time. TBH I can't remember if I even tried it.

Will give it a try tonight & report back 😄 If it does as you describe, that's all I'm after

**Comment by lukeed** [comment]
This is working as expected 😇 My bad. Thanks!

**Comment by paul-tavares** [comment]
it may be worth updating the docs here https://github.com/terkelg/prompts#selectmessage-choices-initial-hint-warn
It does not mention that a function is supported and I just found my self using the `onRender()` to mutate the `choices` - at which point i realized: this can't be the way? 😆 and ended up finding this issue here. A function does in fact work just fine.
