### ISSUE TITLE
Multiselect spams the terminal

### ISSUE THREAD

**Issue by jamen** [terkelg/prompts#89]
Great module! I use this often for small scripts.

I've had an issue with the multiselect, where moving the selection causes it to improperly replace the last lines, and your terminal gets spammed.

![screencast](https://user-images.githubusercontent.com/6251703/45456538-67fa0680-b6a8-11e8-9925-0e08b69973ef.gif)

Edit: I should add I'm using [Alacritty](https://github.com/jwilm/alacritty) terminal.

**Comment by DrunkenPoney** [comment]
I'm not sure but I checked it and I think it's an issue of Alacritty. Alacritty does not seem to listen correctly to ANSI escape sequences.

**Comment by terkelg** [comment]
Hi @jamen! Does this happen for you in other terminals?
@DrunkenPoney do you have experience with Alacritty, what's a possible solution?

**Comment by DrunkenPoney** [comment]
@terkelg 
I downloaded Alacritty expressly for this issue.
I don't know what could be a possible solution, I tried to replace the sistersansi variables with the corresponding ANSI escape sequences following [their ANSI documentation](https://github.com/jwilm/alacritty/blob/master/docs/ansicode.txt). I have to go now but I'll try to find a solution tomorrow.

**Comment by DrunkenPoney** [comment]
I made another test and now I'm pretty sure it's an issue with alacritty itself.
Here is the test I made:
```javascript
const w = str => process.stdout.write(str);

w(`This is the first line\n`);
w(`This is the second line\n`);
w(`And this is the third line`);

// Move cursor one line upward
w(`\u001b[1F`);

// Move cursor to the 12th column (after `the`)
w('\u001b[12G');

// Erase to end of screen
w('\u001b[J');

/* EXPECTED RESULT:
This is the first line
This is the
 */

/* ACTUAL RESULT (with Alacritty):
This is the first line
This is the second line
And this is
 */

// Cursor does not move upward
```

I also ran this in a _normal_ terminal just to be sure and it gave me the expected result.

I'll create an issue on Alacritty repo.

**Comment by DrunkenPoney** [comment]
I tried the same script with the CUU escape sequence (`ESC[A`) and it seems to work.

**Comment by jamen** [comment]
@terkelg @DrunkenPoney I did not see this on other terminals. I figured it had something to do with Alacritty but didn't know where to open the issue.

I tried the changes with my test and it works! But is this more of an Alacritty issue and prompts is more proper without the changes? Either way thanks for investigating it.

[My test, for posterity](https://gist.github.com/jamen/2b3e5f1887fe95fee66a9a29e30af5d0)

**Comment by terkelg** [comment]
I would prefer to keep it simple and not add too much terminal-specific code. It seems like Alacritty is aware of it and working on implementing it. What do you guys think?

**Comment by DrunkenPoney** [comment]
@terkelg I think you're. The issue isn't coming from prompts, it comes from alacritty. In my opinion it would be preferable to not merge my pull request since it replaces a sequence defined by the ANSI standards. It's alacritty that doesn't respect ANSI.

**Comment by jamen** [comment]
Agreed
