### ISSUE TITLE
Ability to update message while waiting for a prompt

### ISSUE THREAD

**Issue by aminnaggar** [terkelg/prompts#92]
First off, I wanted to congratulate you on a super clean lib. I was using inquirer before for another project, and this is noticeably nicer to work with honestly. 👍 

I'm creating a quick registration tool, where I ask new users to enter their email using `prompts`, then sending them an email with a code that I expect them to enter on the CLI. 

These codes have an expiry of 5 minutes, so I wanted to update the message (or have a place to enter text that is updatable without interfering with the prompt itself, perhaps a header) with a countdown of how much time they have to answer. 

How would I be able to do that with `prompts`?
I also would like to know how to cancel a prompt once started (in case the timer runs out)

**Comment by terkelg** [comment]
Published in [v1.2.0](https://github.com/terkelg/prompts/releases/tag/v1.2.0). Thanks!

**Comment by aminnaggar** [comment]
Sorry I wasn't much help, but thank you so much!
